export const action = {
  builtIn: 'builtIn',
  evalObject: 'evalObject',
  getLocationAddress: 'getLocationAddress',
  updateGlobal: 'updateGlobal',
  openCamera: 'openCamera',
  openPhotoLibrary: 'openPhotoLibrary',
  openDocumentManager: 'openDocumentManager',
  pageJump: 'pageJump',
  popUp: 'popUp',
  popUpDismiss: 'popUpDismiss',
  refresh: 'refresh',
  register: 'register',
  removeSignature: 'removeSignature',
  saveObject: 'saveObject',
  saveSignature: 'saveSignature',
  updateObject: 'updateObject',
  scanCamera: 'scanCamera',
} as const

export const actionTypes = Object.values(action)

export const component = {
  button: 'button',
  canvas: 'canvas',
  chart: 'chart',
  chatList: 'chatList',
  ecosDoc: 'ecosDoc',
  divider: 'divider',
  footer: 'footer',
  header: 'header',
  image: 'image',
  label: 'label',
  list: 'list',
  listItem: 'listItem',
  map: 'map',
  page: 'page',
  plugin: 'plugin',
  pluginHead: 'pluginHead',
  pluginBodyTail: 'pluginBodyTail',
  popUp: 'popUp',
  register: 'register',
  select: 'select',
  scrollView: 'scrollView',
  textField: 'textField',
  textView: 'textView',
  video: 'video',
  view: 'view',
  rotation: 'rotation',
  checkbox: 'checkbox',
  richtext: 'richtext',
  search: 'search',
} as const

export const componentKeys = [
  'backgroundColor',
  'borderRadius',
  'chatItem',
  'children',
  'contentType',
  'dataId',
  'dataIn',
  'dataKey',
  'dataModel',
  'ecosObj',
  'height',
  'isEditable',
  'itemObject',
  'iteratorVar',
  'itmeObject',
  'listObject',
  'onChange',
  'onClick',
  'onInput',
  'optionKey',
  'options',
  'path',
  'pathSelected',
  'placeHolder',
  'placeholder',
  'refresh',
  'required',
  'style',
  'text',
  'text=func',
  'textAlign',
  'textBoard',
  'type',
  'viewTag',
  'width',
  'zIndex',
  'chatItem',
] as const

export const componentTypes = Object.values(component)

export const contentTypes = [
  'countryCode',
  'email',
  'file',
  'formattedDate',
  'formattedDuration',
  'hidden',
  'listObject',
  'messageHidden',
  'number',
  'password',
  'passwordHidden',
  'phone',
  'phoneNumber',
  'tel',
  'text',
  'timer',
  'videoSubStream',
] as const

export const deviceTypes = ['web', 'ios', 'android'] as const

export const styleKeys = [
  'FontSize',
  'axis',
  'background',
  'backgroundColor',
  'border',
  'borderColor',
  'borderRadius',
  'borderRaduis',
  'borderWidth',
  'boxShadow',
  'boxSizing',
  'color',
  'contentSize',
  'diaplay',
  'display',
  'filter',
  'float',
  'flex',
  'flexFlow',
  'fontColor',
  'fontFamily',
  'fontSize',
  'fontStyle',
  'fontWeight',
  'foontWeight',
  'height',
  'hieght',
  'isHidden',
  'justifyContent',
  'left',
  'letterSpacing',
  'lineHeight',
  'marginLeft',
  'marginTop',
  'onClick',
  'padding',
  'paddingBottom',
  'paddingLeft',
  'placeholder',
  'position',
  'required',
  'shadow',
  'text-align',
  'textAlign',
  'textDecoration',
  'textIndent',
  'top',
  'width',
  'zIndex',
] as const

export const userEvent = [
  'onBlur',
  'onClick',
  'onChange',
  'onFocus',
  'onHover',
  'onInput',
  'onMouseEnter',
  'onMouseLeave',
  'onMouseOut',
  'onMouseOver',
  'onLazyLoading',
  'onPull' ,
  'onContextmenu',
  "startRecord",
  "pauseRecord",
  "resumeRecord",
  "endRecord",
  "finishRecord",
  "errorRecord",
  "beforeFinish",
  'deleteCallBack',
  'imageClick',
  'onGenerateClick',
  "onCancelClick",
  "onSelectClick",
  "onDateClick"
] as const
